---
title: "My Published Papers"
---

### Click "[PDF]" to download the paper 

#### 2024

**Coming Soon!**

#### 2023

**Johnson, L.G.**, C. Zhai, E.M. Steadham, L.M. Reever, K.J. Prusa, M.N. Nair, E. Huff-Lonergan, and S.M. Lonergan. 2023. Distinct myofibrillar sub-proteomic profiles are associated with the instrumental texture of aged pork loin. <em>Journal of Animal Science</em>. 101:skad327. <https://doi.org/10.1093/jas/skad327> &nbsp; [PDF](myo-jas-2023.pdf)

Zhai, C., S.M. Lonergan, E.J. Huff-Lonergan, **L.G. Johnson**, K. Brown, J.E. Prenni, and M.N. Nair. Lipid peroxidation products influence calpain-1 functionality in vitro by covalent binding. 2023. <em>Journal of Agricultural and Food Chemistry</em>. 71:7836–7846. <br> <https://doi.org/10.1021/acs.jafc.3c01225> &nbsp; [PDF](calpain-1_2023.pdf)

**Johnson, L.G.**, B.M. Patterson, S.M. Lonergan, and E. Huff-Lonergan. Review of postmortem protein oxidation in skeletal muscle and the role of the peroxiredoxin family of endogenous antioxidants. 2023. <em>Meat and Muscle Biology</em>. 6(3): 1-18. <br> <https://doi.org/10.22175/mmb.14492> &nbsp; [PDF](Review-mmb-2023.pdf)

**Johnson, L.G.**, C. Zhai, L.M. Reever, K.J. Prusa, M.N. Nair, E. Huff-Lonergan, and S.M. Lonergan. Characterizing the sarcoplasmic proteome of aged pork chops classified by purge loss. 2023. <em>Journal of Animal Science</em>. 101: 1-12.<br> <https://doi.org/10.1093/jas/skad046> &nbsp; [PDF](jas-2023.pdf)

#### 2021

Patterson, B.M., A.C. Outhouse, E.T. Helm, **L. Johnson**, E.M. Steadham, J.C.M. Dekkers, K.J.Schwartz, N.K. Gabler, S.M. Lonergan, and E. Huff-Lonergan. Novel observations of peroxiredoxin-2 profile and protein oxidation in skeletal muscle from pigs of differing residual feed intake and health status. 2021. <em>Meat and Muscle Biology</em>. 5(1): 1-15.<br> <https://doi.org/10.22175/mmb.12241> &nbsp; [PDF](Novel-mmb-2021.pdf)

**Johnson, L.G.**, E.M. Steadham, E. Huff-Lonergan, and S.M. Lonergan. Partial purification of peroxiredoxin-2 from porcine skeletal muscle. 2021. <em>Meat and Muscle Biology</em>. 5(1): 1-9.<br> <https://doi.org/10.22175/mmb.12408> &nbsp; [PDF](Purification-mmb-2021.pdf)

#### 2020

Schulte, M.D., **L.G. Johnson**, E.A. Zuber, E.M. Steadham, D.A. King, E. Huff-Lonergan, S.M. Lonergan. 2020. Investigation of the sarcoplasmic proteome contribution to the development of pork loin tenderness. <em>Meat and Muscle Biology</em> 4(1): 8, 1-14. <br><https://doi.org/10.22175/mmb.9566> &nbsp; [PDF](Sarco-mmb-2020.pdf)

#### 2019

Schulte, M.D., **L.G. Johnson**, E.A. Zuber, E.M. Steadham, D.A. King, E. Huff-Lonergan, S.M. Lonergan. 2020. Investigation of the sarcoplasmic proteome contribution to the development of pork loin tenderness. <em>Meat and Muscle Biology</em> 4(1): 8, 1-14.<br> <https://doi.org/10.22175/mmb.9566> &nbsp; [PDF](Aging-mmb-2019.pdf)
